import turtle
screen = turtle.Screen()
screen.bgcolor("pink")
m = turtle.Turtle()
m.speed(1)
m.begin_fill()
m.color("yellow")
m.circle(40)
m.pencolor("red")
m.left(-60)
m.forward(60)
m.end_fill()
m.begin_fill()
m.pencolor("red")
m.goto(55, 3)
m.left(60)
m.color("green")
m.circle(40)
m.end_fill()
m.penup()
m.goto(30, -50)
m.pendown()
m.begin_fill()
m.pencolor("red")
m.left(92)
m.forward(150)
m.color("skyblue")
m.left(-90)
m.circle(43)
m.end_fill()
m.penup()
m.goto(27, -50)
m.pendown()
m.begin_fill()
m.pencolor("red")
m.left(100)
m.forward(235)
m.left(-90)
m.color("purple")
m.left(-20)
m.circle(40)
m.end_fill()
m.hideturtle()
turtle.done()
